CSG-634: Update Comet Starter App with Keycloak integration
MetroStar/comet-starter pull request #18
Opened 2023-08-21 21:09 UTC by jbouder

Provide baseline for starter app authentication.

## Description

- Added keycloak config and dependencies
- Updated signin page with SSO button
- Updated auth flow to support SSO signin
- Added Protected Routes component and updated routes as needed

## Related Issue

https://github.com/MetroStar/comet-starter/issues/2

## Motivation and Context

- Provide auth baseline

## How Has This Been Tested?

Local testing, verified e2e testing

## Screenshots (if appropriate):
<img width="569" alt="Screenshot 2023-08-21 at 5 09 00 PM" src="https://github.com/MetroStar/comet-starter/assets/61591423/29568525-49cc-40d3-aa67-f4b076a030a6">

2023-08-22 16:50 UTC, LuisdelaVega requested changes
Posted an idea to minimize boilerplate when using the Protected Route component. Let me know if you agree

2023-08-22 16:50 UTC, LuisdelaVega commented on src/components/protected-route/protected-route.tsx
This component could be implemented like this:

```js
import useAuth from '@src/hooks/use-auth';
import { Navigate, Outlet, Route, RouteProps } from 'react-router-dom';

export const ProtectedRoute = ({ element, path, ...rest }: RouteProps) => {
  const { isSignedIn } = useAuth();

  return (
    <Route element={isSignedIn ? <Outlet /> : <Navigate to="/signin" />}>
      <Route path={path} element={element} {...rest} />
    </Route>
  );
};
```

Then in `App.js` it could be used like this:

```js
export const App = (): React.ReactElement => (
  <RecoilRoot>
    <div>
      <Header />
      <main id="mainSection" className="usa-section">
        <Routes>
          <Route path="/signin" element={<SignIn />} />
          <Route path="/" element={<Home />} />
          <ProtectedRoute path="/dashboard" element={<Dashboard />} />
          <ProtectedRoute path="/details/:id" element={<Details />} />
        </Routes>
      </main>
      <Footer />
    </div>
  </RecoilRoot>
);
```

What do you think?

2023-08-22 16:52 UTC, jbouder commented on src/components/protected-route/protected-route.tsx
Great idea! Exactly the kind of feedback I was looking for.

2023-08-22 17:57 UTC, jbouder commented on src/components/protected-route/protected-route.tsx
Actually, its looking that method might not work. I tried it and am getting the following error: 

_Uncaught Error: [ProtectedRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>_

Which lead me to this: https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f

2023-08-22 17:59 UTC, LuisdelaVega commented on src/components/protected-route/protected-route.tsx
Great! The destructuring of the props in my example `ProtectedRoute` component wasn't really necessary but the idea is what matters lol. A cleaner version would be something like:

```js
export const ProtectedRoute = (props: RouteProps) => {
  const { isSignedIn } = useAuth();

  return (
    <Route element={isSignedIn ? <Outlet /> : <Navigate to="/signin" />}>
      <Route {...props} />
    </Route>
  );
};
```

2023-08-23 11:46 UTC, LuisdelaVega commented on src/components/protected-route/protected-route.tsx
Read through the link you sent. I think it's fine to leave it like you originally had implemented it. We can revisit it in the future but this is not a big enough deal to hold up this PR.

2023-08-23 11:47 UTC, LuisdelaVega approved these changes
Excellent work!

2023-08-24 13:23 UTC, merged